name: Deploy Laravel to Cloud Run

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_CREDENTIALS }}

            - name: Configure Docker for Artifact Registry
                # Region is correct
              run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Build and push image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: europe-west1-docker.pkg.dev/laravel-cloud-475809/stubbr-dev-repo/laravel-app:latest

            - name: Deploy to Cloud Run
              uses: google-github-actions/deploy-cloudrun@v1
              with:
                  service: StubbrDev
                  image: europe-west1-docker.pkg.dev/laravel-cloud-475809/stubbr-dev-repo/laravel-app:latest
                  region: europe-west1